# Generated by Django 5.0.9 on 2026-07-14 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentvisit',
            options={'verbose_name': 'Поквартирный обход', 'verbose_name_plural': 'Поквартирные обходы'},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Кампания', 'verbose_name_plural': 'Кампании'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='apartmentvisit',
            name='apartment_number',
            field=models.PositiveIntegerField(verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='apartmentvisit',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='apartmentvisit',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя контакта'),
        ),
        migrations.AlterField(
            model_name='apartmentvisit',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контакта'),
        ),
        migrations.AlterField(
            model_name='apartmentvisit',
            name='entrance',
            field=models.PositiveIntegerField(verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='apartmentvisit',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='campaigns.house', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='apartmentvisit',
            name='opened_door',
            field=models.BooleanField(verbose_name='Дверь открыли'),
        ),
        migrations.AlterField(
            model_name='apartmentvisit',
            name='reaction',
            field=models.CharField(blank=True, choices=[('positive', 'Позитивно'), ('neutral', 'Нейтрально'), ('negative', 'Негативно')], max_length=20, null=True, verbose_name='Реакция'),
        ),
        migrations.AlterField(
            model_name='apartmentvisit',
            name='visited_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обхода'),
        ),
        migrations.AlterField(
            model_name='apartmentvisit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто обошёл'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='house',
            name='apartments_per_entrance',
            field=models.PositiveIntegerField(verbose_name='Квартир в подъезде'),
        ),
        migrations.AlterField(
            model_name='house',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='campaigns.campaign', verbose_name='Кампания'),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='house',
            name='entrances',
            field=models.PositiveIntegerField(verbose_name='Количество подъездов'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_number',
            field=models.CharField(max_length=20, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.CharField(max_length=200, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
